"""Central GRUB configuration with lessons learned from the Lenovo multiboot project.

Hard requirements encoded here:
- One chef GRUB under EFI/UltimateInstaller (never leave distro GRUB as BootOrder #1)
- Direct linux entries by UUID (no fragile os-prober dependency)
- Stable /vmlinuz and /initrd.img symlinks with relative targets
- Menu timeout visible (never hidden / timeout 0)
- No Advanced submenu clutter
- UEFI Firmware Settings entry last
- Shared swap resume UUID consistent across distros
"""

from __future__ import annotations

from dataclasses import dataclass
from textwrap import dedent

from uli.core.plan import DistroSelection, InstallationPlan, PartitionSpec


DISTRO_CLASS = {
    "debian": "debian",
    "ubuntu": "ubuntu",
    "fedora": "fedora",
    "arch": "arch",
    "cachyos": "arch",
    "endeavouros": "arch",
    "kali": "kali",
    "mint": "linuxmint",
    "proxmox": "debian",
}


@dataclass
class MenuEntry:
    title: str
    class_name: str
    root_uuid: str
    kernel: str = "/vmlinuz"
    initrd: str = "/initrd.img"
    options: str = "ro quiet splash"


def _root_for(plan: InstallationPlan, distro: DistroSelection) -> PartitionSpec:
    for part in plan.partitions:
        if part.role == "root" and part.distribution == distro.id:
            # Prefer matching variant via label when multiple roots of same id exist
            if distro.variant and part.label and distro.variant in part.label:
                return part
            candidate = part
    for part in plan.partitions:
        if part.role == "root" and part.distribution == distro.id:
            return part
    raise KeyError(f"No root partition for {distro.id}")


def _swap_uuid(plan: InstallationPlan) -> str | None:
    for part in plan.partitions:
        if part.role == "swap" and part.uuid:
            return part.uuid
    return None


def build_menu_entries(plan: InstallationPlan) -> list[MenuEntry]:
    swap = _swap_uuid(plan)
    entries: list[MenuEntry] = []
    for distro in plan.distributions:
        root = _root_for(plan, distro)
        uuid = root.uuid or f"PENDING-{root.label}"
        opts = "ro quiet splash"
        if swap:
            opts += f" resume=UUID={swap}"
        entries.append(
            MenuEntry(
                title=distro.display_name,
                class_name=DISTRO_CLASS.get(distro.id, "linux"),
                root_uuid=uuid,
                options=opts,
            )
        )
    return entries


def render_grub_cfg(plan: InstallationPlan) -> str:
    theme = plan.bootloader.theme
    timeout = plan.bootloader.timeout_seconds
    entries = build_menu_entries(plan)

    blocks = [
        dedent(
            f"""\
            # Generated by Ultimate Linux Installer – do not edit by hand
            set timeout={timeout}
            set timeout_style=menu
            set default=0
            loadfont unicode
            insmod all_video
            insmod gfxterm
            insmod png
            set gfxmode=auto
            terminal_output gfxterm
            set theme=/boot/grub/themes/{theme}/theme.txt
            export theme
            """
        )
    ]

    for entry in entries:
        blocks.append(
            dedent(
                f"""\
                menuentry '{entry.title}' --class {entry.class_name} --class gnu-linux --class gnu --class os {{
                    search --no-floppy --fs-uuid --set=root {entry.root_uuid}
                    linux {entry.kernel} root=UUID={entry.root_uuid} {entry.options}
                    initrd {entry.initrd}
                }}
                """
            )
        )

    blocks.append(
        dedent(
            """\
            menuentry 'UEFI Firmware Settings' --id uefi-firmware {
                fwsetup
            }
            """
        )
    )
    return "\n".join(blocks)


def render_kernel_symlink_hook(distro_id: str) -> str:
    """Hook installed into each distro so kernel updates refresh stable root symlinks."""
    if distro_id in {"arch", "cachyos", "endeavouros"}:
        kernel_glob = "vmlinuz-linux*"
        initrd_glob = "initramfs-linux*.img"
        script = dedent(
            f"""\
            #!/usr/bin/env bash
            set -euo pipefail
            # Ultimate Linux Installer – keep /vmlinuz and /initrd.img stable (relative links)
            boot=/boot
            k=$(ls -1 ${{boot}}/{kernel_glob} 2>/dev/null | sort -V | tail -n1 || true)
            i=$(ls -1 ${{boot}}/{initrd_glob} 2>/dev/null | sort -V | tail -n1 || true)
            [[ -n "$k" && -n "$i" ]] || exit 0
            ln -sfr "$k" /vmlinuz
            ln -sfr "$i" /initrd.img
            """
        )
    else:
        script = dedent(
            """\
            #!/usr/bin/env bash
            set -euo pipefail
            # Ultimate Linux Installer – keep /vmlinuz and /initrd.img stable (relative links)
            k=$(ls -1 /boot/vmlinuz-* 2>/dev/null | sort -V | tail -n1 || true)
            i=$(ls -1 /boot/initrd.img-* /boot/initramfs-*.img 2>/dev/null | sort -V | tail -n1 || true)
            [[ -n "$k" && -n "$i" ]] || exit 0
            ln -sfr "$k" /vmlinuz
            ln -sfr "$i" /initrd.img
            """
        )
    return script


def render_efi_bootorder_fix() -> str:
    """Ensure UltimateInstaller remains BootOrder #1 after distro installers meddle."""
    return dedent(
        """\
        #!/usr/bin/env bash
        set -euo pipefail
        # Ultimate Linux Installer – reclaim chef GRUB boot order
        if ! command -v efibootmgr >/dev/null; then
          exit 0
        fi
        mapfile -t entries < <(efibootmgr | sed -n 's/^Boot\\([0-9A-F]*\\).*UltimateInstaller.*/\\1/p')
        if [[ ${#entries[@]} -eq 0 ]]; then
          echo "UltimateInstaller EFI entry not found" >&2
          exit 1
        fi
        chef="${entries[0]}"
        current=$(efibootmgr | sed -n 's/^BootOrder: //p')
        rest=$(echo "$current" | tr ',' '\\n' | grep -vx "$chef" | paste -sd, -)
        if [[ -n "$rest" ]]; then
          efibootmgr -o "${chef},${rest}" >/dev/null
        else
          efibootmgr -o "${chef}" >/dev/null
        fi
        """
    )


def render_fstab_swap_guard(swap_uuid: str) -> str:
    """Prevent slow boot from stale resume UUID (a real failure mode from the laptop project)."""
    return dedent(
        f"""\
        # Ultimate Linux Installer – align resume with shared swap
        mkdir -p /etc/initramfs-tools/conf.d
        echo 'RESUME=UUID={swap_uuid}' > /etc/initramfs-tools/conf.d/resume
        if [[ -f /etc/default/grub ]]; then
          sed -i 's/^GRUB_CMDLINE_LINUX_DEFAULT=.*/GRUB_CMDLINE_LINUX_DEFAULT="quiet splash resume=UUID={swap_uuid}"/' /etc/default/grub || true
        fi
        """
    )


def render_sudo_user_guard(username: str) -> str:
    """Ensure the created user can sudo (Debian pitfall when a root password was set)."""
    return dedent(
        f"""\
        # Ultimate Linux Installer – guarantee sudo for the primary user
        if getent passwd {username} >/dev/null; then
          usermod -aG sudo {username} 2>/dev/null || usermod -aG wheel {username} 2>/dev/null || true
          mkdir -p /etc/sudoers.d
          echo '{username} ALL=(ALL:ALL) ALL' > /etc/sudoers.d/90-uli-{username}
          chmod 440 /etc/sudoers.d/90-uli-{username}
        fi
        """
    )
